### ISSUE TITLE
Crash with new 1.2 release when no environment_groups in config file

### ISSUE THREAD

**Issue by gregkare** [jonlives/knife-spork#78]
Here's a crash that occurs when you don't have an `environment_groups` directive set to a Hash in your `config/spork-config.yml` file. This has been introduced in #75.

```
$ knife spork promote dev database -VV
DEBUG: Using configuration from /Users/kare/code/project/chef-repo/.chef/knife.rb
/Users/kare/.gem/ruby/1.9.3/gems/knife-spork-1.2.0/lib/knife-spork/runner.rb:56:in `load_specified_environment_group': undefined method `[]' for nil:NilClass (NoMethodError)
        from /Users/kare/.gem/ruby/1.9.3/gems/knife-spork-1.2.0/lib/knife-spork/runner.rb:48:in `load_environments_and_cookbook'
        from /Users/kare/.gem/ruby/1.9.3/gems/knife-spork-1.2.0/lib/chef/knife/spork-promote.rb:44:in `run'
        from /Users/kare/.gem/ruby/1.9.3/gems/chef-10.26.0/lib/chef/knife.rb:408:in `run_with_pretty_exceptions'
        from /Users/kare/.gem/ruby/1.9.3/gems/chef-10.26.0/lib/chef/knife.rb:168:in `run'
        from /Users/kare/.gem/ruby/1.9.3/gems/chef-10.26.0/lib/chef/application/knife.rb:123:in `run'
        from /Users/kare/.gem/ruby/1.9.3/gems/chef-10.26.0/bin/knife:25:in `<top (required)>'
        from /Users/kare/.gem/ruby/1.9.3/bin/knife:19:in `load'
        from /Users/kare/.gem/ruby/1.9.3/bin/knife:19:in `<main>'
        from /Users/kare/.gem/ruby/1.9.3/bin/ruby_noexec_wrapper:14:in `eval'
        from /Users/kare/.gem/ruby/1.9.3/bin/ruby_noexec_wrapper:14:in `<main>'
```
